# Generated by Django 4.0.2 on 2022-02-08 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postitem',
            name='image',
        ),
    ]
