# Generated by Django 4.0.2 on 2022-02-10 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0002_remove_postitem_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='postitem',
            name='image',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
